Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/08/2020
Var
// Seção de Declarações das variáveis 
   funcao fprg_MostraMsg : caracter
   inicio
     retorne ("Alo Mundo.")
   fimfuncao

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva (fprg_MostraMsg)

Fimalgoritmo